💎 Julius on the team!
primer/primer.style pull request #244
Opened 2021-06-01 19:06 UTC by tallys

💎 
Copied from Slack - so should be: 

name: Julius Yanik
handle: @juliusschaeper
title: Systems Designer
What drew you into design systems?
Being able to focus on the key elements of design, form, color and typography.
Who have you learned from or been inspired by?
Having an education in industrial design, the Bauhaus design philosophy and Dieter Rams inspired me a lot. Everything I know about digital product design I learned at Wunderlist, which design team was very inspiring.
Favorite tools?
Remarkable tablet, Figma, Origami, Glyphs, GitHubs internal color tool.

2021-06-01 20:11 UTC, yaili requested changes
Just a small word change, but I have a question: we're supposed to add ourselves to the top of the list (so most recent team addition first), is that the order Julius's name will show up?

2021-06-01 20:11 UTC, yaili commented on src/data/team.js
> +    questionTwo: `Having an education in industrial design, the Bauhaus design philosophy and Dieter Rams inspired me a lot. Everything I know about digital product design I learned at Wunderlist, wh
```suggestion
    questionTwo: `Having an education in industrial design, the Bauhaus design philosophy and Dieter Rams inspired me a lot. Everything I know about digital product design I learned at Wunderlist, whose design team was very inspiring.`,
```

2021-06-01 20:14 UTC, tallys commented
Oh! I didn't know there was a rule to the order, yeah! I will rearrange myself as well :)

2021-06-02 03:34 UTC, colebemis approved these changes

2021-06-02 14:47 UTC, yaili approved these changes
🚢

2021-06-02 15:09 UTC, merged